insert into TO_DO (ID,USERNAME,DESCRIPTION,TARGET_DATE, DONE)
values(10001,'Akshitha','Get AWS CERTIFIED',CURRENT_DATE(),false);

insert into TO_DO (ID,USERNAME,DESCRIPTION,TARGET_DATE, DONE)
values(10002,'Vinay','Get TERRAFORM CERTIFIED',CURRENT_DATE(),false);


insert into TO_DO (ID,USERNAME,DESCRIPTION,TARGET_DATE, DONE)
values(10003,'Sahana','Get Salesforce CERTIFIED',CURRENT_DATE(),false);